# Generated by Django 5.2.1 on 2025-05-18 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackedElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("css_selector", models.TextField()),
                ("element_name", models.CharField(max_length=255)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tracked_elements",
            },
        ),
        migrations.CreateModel(
            name="TrackedWebsite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tracked_websites",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.CharField(max_length=255, unique=True)),
                ("username", models.CharField(max_length=100)),
                ("password_hash", models.TextField()),
                ("last_login_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="ElementChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.trackedelement",
                    ),
                ),
            ],
            options={
                "db_table": "element_changes",
            },
        ),
        migrations.AddField(
            model_name="trackedelement",
            name="website",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.trackedwebsite"
            ),
        ),
        migrations.CreateModel(
            name="UserElementUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("update_time", models.DateTimeField()),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.trackedelement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.trackedwebsite",
                    ),
                ),
            ],
            options={
                "db_table": "user_element_updates",
                "indexes": [
                    models.Index(
                        fields=["user", "update_time"],
                        name="idx_user_updates_user_time",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTrackedWebsites",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.trackedwebsite",
                    ),
                ),
            ],
            options={
                "db_table": "user_tracked_websites",
                "unique_together": {("user", "website")},
            },
        ),
    ]
