services:
  backend:
    build:
      context: .
      dockerfile: ./src/backend/django_app/Backend.Dockerfile
    volumes:
      - ./src/backend/django_app:/app/src/backend/django_app
      - ./src/backend/django_app/imgs:/app/imgs
    depends_on:
      - frontend
      - gotify
    environment:
      - DOCKER_ENV=true
      - PYTHONPATH=/app
      - GOTIFY_URL=http://gotify
      - GOTIFY_PORT=80
    ports:
      - "8000:8000"
    working_dir: /app/src/backend

  frontend:
    build:
      context: ./nm-frontend
      dockerfile: Client.Dockerfile
    ports:
      - "4000:4000"

  gotify:
    env_file:
      - ./src/backend/django_app/.env
    image: gotify/server
    ports:
      - "8181:80"
    volumes:
      - ./gotify_data:/app/data
    restart: unless-stopped

volumes:
  backend-db: