services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
  frontend:
    build:
      context: context: ./nm-frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
