FROM python:3.12.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y wkhtmltopdf

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ /app/src/

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x entrypoint.sh
ENTRYPOINT [ "/app/entrypoint.sh" ]
