# Generated by Django 5.2.1 on 2025-05-21 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackedElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cssSelector", models.TextField()),
                ("elementName", models.CharField(max_length=255)),
                ("registeredAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tracked_elements",
            },
        ),
        migrations.CreateModel(
            name="TrackedWebsite",
            fields=[
                (
                    "siteId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("siteName", models.CharField(max_length=30, unique=True)),
                ("siteUrl", models.TextField()),
                ("siteDescription", models.TextField(max_length=300)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tracked_websites",
            },
        ),
        migrations.CreateModel(
            name="UserTrackedWebsites",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("addedAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_tracked_websites",
            },
        ),
        migrations.CreateModel(
            name="ElementChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("change", models.TextField(null=True)),
                ("detectedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.trackedelement",
                    ),
                ),
            ],
            options={
                "db_table": "element_changes",
            },
        ),
        migrations.AddField(
            model_name="trackedelement",
            name="website",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tracking.trackedwebsite",
            ),
        ),
        migrations.CreateModel(
            name="UserElementUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("statusCode", models.CharField(max_length=100)),
                ("updateTime", models.DateTimeField()),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.trackedelement",
                    ),
                ),
            ],
            options={
                "db_table": "user_element_updates",
            },
        ),
    ]
