# Generated by Django 5.2.1 on 2025-05-30 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Observer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("f7dafc33-2f81-4abf-8d35-6a8456b464db"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "observers",
            },
        ),
        migrations.CreateModel(
            name="TrackedElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cssSelector", models.TextField()),
                ("elementName", models.CharField(max_length=255)),
                ("registeredAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tracked_elements",
            },
        ),
        migrations.CreateModel(
            name="ObserverInfo",
            fields=[
                (
                    "observer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="tracking.observer",
                    ),
                ),
                ("info", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "observers_info",
            },
        ),
        migrations.AddField(
            model_name="observer",
            name="element",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tracking.trackedelement",
            ),
        ),
        migrations.CreateModel(
            name="ElementChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("textChange", models.TextField(null=True)),
                ("imageChangeUrl", models.TextField(null=True)),
                ("detectedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.trackedelement",
                    ),
                ),
            ],
            options={
                "db_table": "element_changes",
            },
        ),
        migrations.CreateModel(
            name="TrackedWebsite",
            fields=[
                (
                    "siteId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("siteName", models.CharField(max_length=30)),
                ("siteUrl", models.TextField()),
                ("siteDescription", models.TextField(max_length=900)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("json", "JSON"),
                            ("image", "image"),
                        ],
                        default="html",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tracked_websites",
                "indexes": [models.Index(fields=["siteName"], name="idx_site_name")],
            },
        ),
        migrations.AddField(
            model_name="trackedelement",
            name="website",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tracking.trackedwebsite",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="UserElementUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("statusCode", models.CharField(max_length=100)),
                ("updateTime", models.DateTimeField()),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.trackedelement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.trackedwebsite",
                    ),
                ),
            ],
            options={
                "db_table": "user_element_updates",
                "indexes": [
                    models.Index(
                        fields=["user", "updateTime"], name="idx_user_updates_user_time"
                    ),
                    models.Index(fields=["website"], name="idx_website"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTrackedWebsites",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("addedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.trackedwebsite",
                    ),
                ),
            ],
            options={
                "db_table": "user_tracked_websites",
                "unique_together": {("user", "website")},
            },
        ),
    ]
