# Generated by Django 5.2.1 on 2025-05-21 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userelementupdate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userelementupdate",
            name="website",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tracking.trackedwebsite",
            ),
        ),
        migrations.AddField(
            model_name="usertrackedwebsites",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="usertrackedwebsites",
            name="website",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tracking.trackedwebsite",
            ),
        ),
        migrations.AddIndex(
            model_name="userelementupdate",
            index=models.Index(
                fields=["user", "updateTime"], name="idx_user_updates_user_time"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usertrackedwebsites",
            unique_together={("user", "website")},
        ),
    ]
