# Generated by Django 5.2.1 on 2025-05-30 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2c6f5536-0756-4952-98b4-327e1f2f141e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="trackedelement",
            name="cssSelector",
            field=models.TextField(null=True),
        ),
    ]
