# Generated by Django 5.2.1 on 2025-05-30 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_alter_observer_id_alter_trackedelement_cssselector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("22940dbc-7952-416f-8fff-8a31809e4129"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
