# Generated by Django 5.2.1 on 2025-05-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedelement",
            name="website",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tracking.trackedwebsite",
                unique=True,
            ),
        ),
    ]
