# Generated by Django 5.2.1 on 2025-05-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_alter_trackedelement_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedwebsite",
            name="siteName",
            field=models.CharField(max_length=30),
        ),
    ]
