# Generated by Django 5.2.1 on 2025-05-30 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_alter_observer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9d7531a5-7f2a-43f8-a76e-b57ad09a6243"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
