# Generated by Django 5.2.1 on 2025-05-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_alter_trackedwebsite_sitename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedwebsite",
            name="siteDescription",
            field=models.TextField(max_length=1000),
        ),
    ]
