# Generated by Django 5.2.1 on 2025-05-30 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_alter_observer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("bfb9c7bf-9284-413a-b067-439dd9aa3fe7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
