# Generated by Django 5.2.1 on 2025-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0005_alter_trackedwebsite_sitedescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedwebsite",
            name="siteDescription",
            field=models.TextField(max_length=900),
        ),
    ]
