# Generated by Django 5.2.1 on 2025-05-30 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0005_alter_observer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1452cc04-21ee-43be-aabe-2ee307f99d4b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
