# Generated by Django 5.2.1 on 2025-05-24 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0006_alter_trackedwebsite_sitedescription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userelementupdate",
            index=models.Index(fields=["website"], name="idx_website"),
        ),
    ]
