# Generated by Django 5.2.1 on 2025-05-30 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0006_alter_observer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userelementupdate",
            name="error",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="observer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9d500964-4266-48a3-b9c1-d865644615b5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
