# Generated by Django 5.2.1 on 2025-05-30 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0007_userelementupdate_error_alter_observer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observer",
            name="element",
        ),
        migrations.AddField(
            model_name="observer",
            name="site",
            field=models.ForeignKey(
                default=uuid.uuid4(),
                on_delete=django.db.models.deletion.CASCADE,
                to="tracking.trackedwebsite",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="observer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("430c1f9f-38e8-441b-881b-f94d082c3deb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
