# Generated by Django 5.2.1 on 2025-05-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0007_userelementupdate_idx_website"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="trackedwebsite",
            index=models.Index(fields=["siteName"], name="idx_site_name"),
        ),
    ]
