# Generated by Django 5.2.1 on 2025-05-30 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0008_remove_observer_element_observer_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observer",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ac3ffaf1-a306-47ab-a35b-9f25873d16de"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
