# Generated by Django 5.2.1 on 2025-05-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0009_alter_observer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observer",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
