# Generated by Django 5.2.1 on 2025-05-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0010_alter_observer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedelement",
            name="jsonSelector",
            field=models.TextField(null=True),
        ),
    ]
