# Generated by Django 5.2.1 on 2025-05-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0011_trackedelement_jsonselector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
