# Generated by Django 5.2.1 on 2025-05-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0012_alter_observer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observer",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tracking.trackedwebsite",
                unique=True,
            ),
        ),
    ]
