# Generated by Django 5.2.1 on 2025-05-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0013_alter_observer_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="observer",
            name="hash",
            field=models.CharField(null=True),
        ),
    ]
