# Generated by Django 5.2.1 on 2025-06-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0015_gotifyinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gotifyinfo",
            name="updateTime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
