# Generated by Django 5.2.1 on 2025-06-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0016_alter_gotifyinfo_updatetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gotifyinfo",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
