# Generated by Django 5.2.1 on 2025-06-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0017_alter_gotifyinfo_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackedelement",
            name="cssSelector",
        ),
        migrations.RemoveField(
            model_name="trackedelement",
            name="jsonSelector",
        ),
        migrations.AddField(
            model_name="trackedelement",
            name="selector",
            field=models.TextField(default="none"),
            preserve_default=False,
        ),
    ]
