# Generated by Django 5.2.1 on 2025-06-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0018_remove_trackedelement_cssselector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elementchange",
            name="imageChangeUrl",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
