# Generated by Django 5.2.1 on 2025-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0019_alter_elementchange_imagechangeurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elementchange",
            name="imageChangeUrl",
            field=models.CharField(null=True),
        ),
    ]
