# Generated by Django 5.2.1 on 2025-06-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0020_alter_elementchange_imagechangeurl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trackedwebsite",
            old_name="type",
            new_name="siteType",
        ),
    ]
