"""
Django settings for django_app project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os,sys
from pathlib import Path
from django.conf.global_settings import CSRF_COOKIE_SAMESITE, SESSION_COOKIE_SAMESITE, CSRF_COOKIE_HTTPONLY, \
    SESSION_COOKIE_HTTPONLY, SESSION_COOKIE_AGE, SESSION_SAVE_EVERY_REQUEST, SESSION_COOKIE_SECURE
MEDIA_URL='/imgs/'
BASE_DIR = Path(__file__).resolve().parent.parent
if os.environ.get('DOCKER_ENV'):
    MEDIA_ROOT = '/app/imgs'
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'imgs')
DOMAIN='http://localhost:8000'
sys.path.insert(0, str(BASE_DIR.parent.parent))
sys.path.insert(0, str(BASE_DIR.parent.parent / "observing"))
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = bool(int(os.getenv("DEBUG", default=1)))
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1").split(",")
AUTH_USER_MODEL = 'users.User'

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    'django.contrib.sessions',
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "tracking",
    "rest_framework",
    "corsheaders",
]


MIDDLEWARE = [
"corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
CSRF_COOKIE_SAMESITE='Lax'
SESSION_COOKIE_SAMESITE='Lax'
CSRF_COOKIE_HTTPONLY=False
SESSION_COOKIE_HTTPONLY=True
ROOT_URLCONF = "django_app.urls"
SESSION_COOKIE_AGE=2*60*60
SESSION_SAVE_EVERY_REQUEST=True
SESSION_COOKIE_SECURE=False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
REST_FRAMEWORK ={
    'DEFAULT_RENDERER_CLASSES':[
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES':[
       # 'rest_framework.authentication.SessionAuthentication',
        'django_app.custom_session.CustomSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES':[
       # 'rest_framework.authentication.SessionAuthentication',
        'django_app.custom_authentication.CustomIsAuthenticated',
    ],
    "EXCEPTION_HANDLER": "django_app.exception_handler.custom_exception_handler"
}


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        #"NAME": BASE_DIR / "db.sqlite3",
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'OPTIONS':{
            'timeout': 20,
            'init_command': 'PRAGMA journal_mode=WAL;',  
        }
    }
}

CONN_MAX_AGE = 0
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4000",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:4000",
]